title: Zhangyu Zhu # your name (or website title) here
logo: <img src="/images/photo.png" width="100" height="100">  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Introduction 
  <br><br>
  Currently pursuing Masters in Business Analytics at the University of Rochester. 
  <br><br>
  Had experience about get insights from analyze large datasets using multiple tools and building causal & predictive models to help address business problems. 
  <br><br>
  <a href="http://www.linkedin.com/in/zhangyuzhu">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
